updateuserbtn="//td[contains(text(),'Update User')]"
inputemailfield="//input[contains(@name,'EmailId')]"
searchbutton="//div[contains(text(),'Search')]"
selectuserresult="//tr[@role='listitem' and @aria-setsize='1']"
addressonefield="(//label[text()='Address 1']/following::input[@type='TEXT'])[1]"
savebtn="//div[contains(text(),'Save')]"
okbtn="//td[contains(@class,'button')]//div[contains(text(),'OK')]"
popupmessage="//div[contains(@eventproxy,'globalWarn')]//td[contains(text(),'')]"
