careteammembers_button_xpath = "//md-card[@id='myCareCard']"
careteamname_button_xpath = "//input[@name='careTeam']"
selectcareteam_button_xpath = "//li[@tabindex='0']"
careteamsave_button_xpath = "//gsi-save-md-button[@id='btnSaveCareTeam'][@aria-disabled='false']//span[text()='Save']"
careteamaftersave_button_xpath = "//gsi-save-md-button[@id='btnSaveCareTeam'][@aria-disabled='true']//span[text()='Save']"
createaseperatecareteam_button_xpath = "//span[text()='Create Separate Team']"
careteamchangeforall_button_xpath = "//span[text()='Change for All']"
chooseacareteam_textbox_xpath = "//input[@aria-label='Choose a New Team']"
removecareteamverticaldot_button_xpath = "//button[@id='directMenu']"
removecareteam_button_xpath = "//md-icon[@aria-label='delete']"
unassignedcareteames_button_xpath = "//p[contains(text(),'unassign the Care Team')]//ancestor::md-dialog/md-dialog-actions/button/span[text()='yes']"
consentadvisory_button_xpath = "//button[@class='md-primary md-button md-ink-ripple']/span"
careteamwizardclose_button_xpath = "//button[@class='md-icon-button md-button md-ink-ripple flex-nogrow']"