search_patient_button_xpath = "//div[@id='navbuttons_search']"
patientid_text_xpath = "//td/input[@name='mrn']"
lookup_button_xpath = "//td/input[@name='lookup']"
Address_field_xpath = "//td[contains(text(),'Address Street:')]//following::table[@class='dataVal']//td[normalize-space(text())]"
encounter_tab_xpath ="//a[contains(text(),'Encounter Information')]"
encounter_edit_icon_xpath="//a[@title='Edit Encounter']"
room_input_xpath ="//input[@id='locationroom']"
encounter_save_button_xpath ="//input[@value='Save']"
admitdate="//input[contains(@id,'addate')]"
dischargedate="//input[contains(@id,'disdate')]"
admitdatecal="//img[contains(@onclick,'addate')]"
dischargedatecal="//img[contains(@onclick,'disdate')]"
