ccp_link_text="CCP"
ccp_issue_link_text="QA"
ccp_issuetitle_input_xpath="//input[@name='title']"
ccp_inprogressgoal_intend_xpath="//td[contains(text(),'In progress Goals')]//preceding-sibling::td"
ccp_inprogressgoal_Editgoal_xpath="//*[@title='Edit this goal']"
ccp_goalstartdate_xpath="//*[@id='goal_startDate']"
ccp_goalsave_xpath="//*[@id='saveGoal']"
ccp_inprogressintervention_xpath="//td[contains(text(),'In progress Interventions')]//preceding-sibling::td"
ccp_inprogressintervention_Editintervention_xpath="//*[@title='Edit this intervention']"
ccp_interventionstartdate_xpath="//*[@id='interventionStartDate1']"
ccp_interventionsave_xpath="//*[@id='saveIntervention']"