logout_image_xpath = "//md-icon[@aria-label='logout']"
logout_button_xpath = "//div[text()='Yes']"
home_button_xpath = "//*[@id = 'appHome_menu']"
demographics_button_xpath = "//div[@id='appEnrollment_menu']"
careplan_button_xpath = "//*[@id = 'appCareplan_menu']"
populationmanager_button_xpath = "//div[@id='appPopManager_menu']"
messageapp_button_xpath = "//*[@id='appMessages_menu']"
alertapp_button_xpath = "//div[@id='appAlerts_menu']"
admin_icon = "//div[@id='appAdmin_menu']"
taskoverduecount_button_xpath = "//div[@id='overdueTaskCount']"
tasklistbadge_button_xpath = "//div[@id='appTaskList_badge']"
carebook_firstname_textbox_xpath = "//input[@placeholder='First name']"
carebook_lastname_textbox_xpath = "//input[@placeholder='Last name*']"
carebook_search_button_xpath="//md-icon[@aria-label='magnify']"
task_button_xpath = "//div[@id='appTaskList_menu']"
reset_button_xpath = "//span[normalize-space(text()) = 'Reset']"