verticaldotlinetodeleteprogram_button_xpath = "//gsi-program-table//md-icon[@md-svg-icon='dots-vertical']"
statuseffectivedate_textbox_xpath = "//input[@class='md-datepicker-input']"
addnewprogram_button_xpath = "//button[@aria-label='Add a new program']"
programsave_button_xpath = "//gsi-save-md-button[@id='btnSaveProgram'][@aria-disabled='false']//span[text()='Save']"
programaftersave_button_xpath = "//gsi-save-md-button[@id='btnSaveProgram'][@aria-disabled='true']//span[text()='Save']"
parentprogram_dropdown_xpath = "//md-select[@name='parentProgramName']"
programname_dropdown_xpath = "//md-select[@name='programName']"
parentprogramfirstvalue_button_xpath = "//md-option[contains(@ng-disabled,'ParentProgram')]/div"
subprogramplusicon_button_xpath = "//button[@aria-label='Expand to see child programs']"
childprogramfirstvalue_button_xpath = "//md-option[contains(@ng-repeat,'SubProgram')]/div"
consentselectstatus_dropdown_xpath="//md-select[@name='consent']//div[text()='Select Status']"
consentstatusfirstvalue_button_xpath = "//md-option[@ng-repeat='opt in programConsentPanel.app.consentList'][1]"
consenter_dropdown_xpath = "//*[@name='consenter'][@aria-label='Consenter']"
consenterfirstvalue_button_xpath = "//div[@class='md-select-menu-container md-active md-clickable']//div[@class='md-text ng-binding'][1]"
consentfinish_button_xpath = "//button[@id='btnSaveConsent']/span[text()='Finish']"
childprogram_button_xpath = "//label[@class='sub-program-chip ng-binding ng-scope']"
programstatus_dropdown_xpath = "//md-select[@name='status']"
programstatusfirstvalue_button_xpath = "//md-option[@ng-repeat='opt in ctrl.data.program.statuses']"
programendreason_dropdown_xpath = "//md-select[@name='endReason']"
programendreasonfirstvalue_button_xpath = "//md-option[@ng-repeat='opt in ctrl.getEndReasonOptions() | filter:endReasonFilter()'][1] | //md-option[@ng-repeat='opt in ctrl.data.program.endReasons'][1]"
